extends Node2D


# Called every frame. 'delta' is the elapsed time since the previous frame.
func _process(delta):
	match State.clock:
		200:
			%PresRec.hide()
			%PamRec.hide()
			%JimRec.hide()
			%KidsRec.hide()
			%JRPGRec.hide()
			%SciRec.hide()
			
		0:
			%PresRec.hide()
			%PamRec.hide()
			%JimRec.show()
			%KidsRec.hide()
			%JRPGRec.hide()
			%SciRec.hide()
		1:
			%PresRec.hide()
			%PamRec.hide()
			%JimRec.hide()
			%KidsRec.hide()
			%JRPGRec.hide()
			%SciRec.hide()
		2:
			%PresRec.hide()
			%PamRec.hide()
			%JimRec.hide()
			%KidsRec.hide()
			%JRPGRec.show()
			%SciRec.hide()
		3:
			%PresRec.hide()
			%PamRec.hide()
			%JimRec.hide()
			%KidsRec.hide()
			%JRPGRec.hide()
			%SciRec.hide()
		4:
			%PresRec.hide()
			%PamRec.hide()
			%JimRec.hide()
			%KidsRec.hide()
			%JRPGRec.hide()
			%SciRec.show()
		5:
			%PresRec.hide()
			%PamRec.hide()
			%JimRec.hide()
			%KidsRec.hide()
			%JRPGRec.hide()
			%SciRec.hide()
		6:
			%PresRec.hide()
			%PamRec.show()
			%JimRec.hide()
			%KidsRec.hide()
			%JRPGRec.hide()
			%SciRec.hide()
		7:
			%PresRec.hide()
			%PamRec.hide()
			%JimRec.hide()
			%KidsRec.hide()
			%JRPGRec.hide()
			%SciRec.hide()
		8:
			%PresRec.show()
			%PamRec.hide()
			%JimRec.hide()
			%KidsRec.hide()
			%JRPGRec.hide()
			%SciRec.hide()
		9:
			%PresRec.hide()
			%PamRec.hide()
			%JimRec.hide()
			%KidsRec.hide()
			%JRPGRec.hide()
			%SciRec.hide()
		10:
			%PresRec.hide()
			%PamRec.hide()
			%JimRec.hide()
			%KidsRec.show()
			%JRPGRec.hide()
			%SciRec.hide()
		11:
			%PresRec.hide()
			%PamRec.hide()
			%JimRec.hide()
			%KidsRec.hide()
			%JRPGRec.hide()
			%SciRec.hide()
